In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

In [3]:
customers = pd.read_csv("../data/raw/customers_data.csv")
products = pd.read_csv("../data/raw/products_data.csv")
sales = pd.read_csv("../data/raw/sales_data.csv")

In [4]:
print("Customers :", customers.shape)
print("Products  :", products.shape)
print("Sales     :", sales.shape)

Customers : (5, 7)
Products  : (5, 5)
Sales     : (5, 7)

In [5]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  5 non-null      int64
 1   Name         5 non-null      str
 2   Age          5 non-null      int64
 3   Gender       5 non-null      str
 4   Location     5 non-null      str
 5   Join_Date    5 non-null      str
 6   Total_Spent  5 non-null      float64
dtypes: float64(1), int64(2), str(4)
memory usage: 412.0 bytes

In [6]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    5 non-null      int64
 1   Product_Name  5 non-null      str
 2   Category      5 non-null      str
 3   Price         5 non-null      float64
 4   Brand         5 non-null      str
dtypes: float64(1), int64(1), str(3)
memory usage: 332.0 bytes

In [7]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sale_ID      5 non-null      int64
 1   Product_ID   5 non-null      int64
 2   Customer_ID  5 non-null      int64
 3   Date         5 non-null      str
 4   Quantity     5 non-null      int64
 5   Sale_Price   5 non-null      float64
 6   Channel      5 non-null      str
dtypes: float64(1), int64(4), str(2)
memory usage: 412.0 bytes

In [8]:
customers.describe()

       Customer_ID        Age  Total_Spent
count     5.000000   5.000000     5.000000
mean   2003.000000  28.400000   520.000000
std       1.581139   4.722288   168.077363
min    2001.000000  22.000000   300.000000
25%    2002.000000  27.000000   450.000000
50%    2003.000000  28.000000   500.000000
75%    2004.000000  30.000000   600.000000
max    2005.000000  35.000000   750.000000

In [9]:
products.describe()

       Product_ID       Price
count    5.000000    5.000000
mean   103.000000   54.500000
std      1.581139   42.441136
min    101.000000   22.500000
25%    102.000000   25.000000
50%    103.000000   30.000000
75%    104.000000   75.000000
max    105.000000  120.000000

In [10]:
sales.describe()

        Sale_ID  Product_ID  Customer_ID  Quantity  Sale_Price
count  5.000000    5.000000      5.00000   5.00000    5.000000
mean   3.000000  103.000000   2002.20000   1.80000   64.000000
std    1.581139    1.581139      1.30384   0.83666   35.249113
min    1.000000  101.000000   2001.00000   1.00000   30.000000
25%    2.000000  102.000000   2001.00000   1.00000   45.000000
50%    3.000000  103.000000   2002.00000   2.00000   50.000000
75%    4.000000  104.000000   2003.00000   2.00000   75.000000
max    5.000000  105.000000   2004.00000   3.00000  120.000000

In [11]:
print("Customers")
display(customers.isna().sum())

print("Products")
display(products.isna().sum())

print("Sales")
display(sales.isna().sum())

Customers

Customer_ID    0
Name           0
Age            0
Gender         0
Location       0
Join_Date      0
Total_Spent    0
dtype: int64

Products

Product_ID      0
Product_Name    0
Category        0
Price           0
Brand           0
dtype: int64

Sales

Sale_ID        0
Product_ID     0
Customer_ID    0
Date           0
Quantity       0
Sale_Price     0
Channel        0
dtype: int64

In [12]:
print("Customers duplicates :", customers.duplicated().sum())
print("Products duplicates  :", products.duplicated().sum())
print("Sales duplicates     :", sales.duplicated().sum())

Customers duplicates : 0
Products duplicates  : 0
Sales duplicates     : 0

In [13]:
customers["Join_Date"] = pd.to_datetime(
    customers["Join_Date"],
    errors="coerce"
)

sales["Date"] = pd.to_datetime(
    sales["Date"],
    errors="coerce"
)

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
customers = pd.read_csv("../data/raw/customers_data.csv")
products = pd.read_csv("../data/raw/products_data.csv")
sales = pd.read_csv("../data/raw/sales_data.csv")

In [6]:
customers.shape
products.shape
sales.shape

(5, 7)

In [7]:
customers.info()
products.info()
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  5 non-null      int64
 1   Name         5 non-null      str
 2   Age          5 non-null      int64
 3   Gender       5 non-null      str
 4   Location     5 non-null      str
 5   Join_Date    5 non-null      str
 6   Total_Spent  5 non-null      float64
dtypes: float64(1), int64(2), str(4)
memory usage: 412.0 bytes
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    5 non-null      int64
 1   Product_Name  5 non-null      str
 2   Category      5 non-null      str
 3   Price         5 non-null      float64
 4   Brand         5 non-null      str
dtypes: float64(1), int64(1), str(3)
memory usage: 332.0 bytes
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sale_ID      5 non-null      int64
 1   Product_ID   5 non-null      int64
 2   Customer_ID  5 non-null      int64
 3   Date         5 non-null      str
 4   Quantity     5 non-null      int64
 5   Sale_Price   5 non-null      float64
 6   Channel      5 non-null      str
dtypes: float64(1), int64(4), str(2)
memory usage: 412.0 bytes

In [8]:
customers.describe()
products.describe()
sales.describe()

        Sale_ID  Product_ID  Customer_ID  Quantity  Sale_Price
count  5.000000    5.000000      5.00000   5.00000    5.000000
mean   3.000000  103.000000   2002.20000   1.80000   64.000000
std    1.581139    1.581139      1.30384   0.83666   35.249113
min    1.000000  101.000000   2001.00000   1.00000   30.000000
25%    2.000000  102.000000   2001.00000   1.00000   45.000000
50%    3.000000  103.000000   2002.00000   2.00000   50.000000
75%    4.000000  104.000000   2003.00000   2.00000   75.000000
max    5.000000  105.000000   2004.00000   3.00000  120.000000

In [9]:
customers.isna().sum()
products.isna().sum()
sales.isna().sum()

Sale_ID        0
Product_ID     0
Customer_ID    0
Date           0
Quantity       0
Sale_Price     0
Channel        0
dtype: int64

In [11]:
customers["Join_Date"] = pd.to_datetime(
    customers["Join_Date"],
    errors="coerce"
)

sales["Date"] = pd.to_datetime(
    sales["Date"],
    errors="coerce"
)

In [13]:
customers[(customers["Age"] < 0) | (customers["Age"] > 100)]

Empty DataFrame
Columns: [Customer_ID, Name, Age, Gender, Location, Join_Date, Total_Spent]
Index: []

In [14]:
customers = customers.drop_duplicates()
products = products.drop_duplicates()
sales = sales.drop_duplicates()

In [16]:
sales["Total_Amount"] = sales["Quantity"] * sales["Sale_Price"]